package stockgestion;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Clément
 */
public class stock extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    
    public stock() {
        initComponents();
        Table();
        Table2();
    }
    
    public void Connect(){
        try{
            Class.forName("com.mysql.jdbc.Driver");//utilisation d'une librairie pour la connexion mysql
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/gestion","root","");//Connexion a la base de données
        }catch(Exception e){
            e.printStackTrace();//Afficher l'érreur
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtetat = new javax.swing.JComboBox<>();
        txtid = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        buttonmodifier = new javax.swing.JButton();
        buttonsupprimer = new javax.swing.JButton();
        buttonajouter = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtidart = new javax.swing.JTextField();
        txtnomart = new javax.swing.JTextField();
        txtquantite = new javax.swing.JTextField();
        txtreference = new javax.swing.JTextField();
        buttonmodifier1 = new javax.swing.JButton();
        buttonsupprimer1 = new javax.swing.JButton();
        buttonajouter1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administration");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Prenom :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Mail :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Etat :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nom :");

        txtetat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtetat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Valid", "Banni" }));
        txtetat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtetat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtetatActionPerformed(evt);
            }
        });

        txtid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtnom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });

        txtmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmailActionPerformed(evt);
            }
        });

        txtprenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtprenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomActionPerformed(evt);
            }
        });

        buttonmodifier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonmodifier.setText("MODIFIER");
        buttonmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmodifierActionPerformed(evt);
            }
        });

        buttonsupprimer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonsupprimer.setForeground(new java.awt.Color(204, 0, 0));
        buttonsupprimer.setText("SUPPRIMER");
        buttonsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsupprimerActionPerformed(evt);
            }
        });

        buttonajouter.setBackground(new java.awt.Color(255, 255, 255));
        buttonajouter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonajouter.setForeground(new java.awt.Color(102, 255, 102));
        buttonajouter.setText("AJOUTER");
        buttonajouter.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                buttonajouterComponentShown(evt);
            }
        });
        buttonajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonajouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtid))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtnom))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtprenom))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(buttonajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtmail)
                            .addComponent(txtetat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtetat)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Administrateur", jPanel1);

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gestion des Stocks");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("ID :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Reference :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Quantité :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Nom :");

        txtidart.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidartActionPerformed(evt);
            }
        });

        txtnomart.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnomart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomartActionPerformed(evt);
            }
        });

        txtquantite.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtquantite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantiteActionPerformed(evt);
            }
        });

        txtreference.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtreference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreferenceActionPerformed(evt);
            }
        });

        buttonmodifier1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonmodifier1.setText("MODIFIER");
        buttonmodifier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmodifier1ActionPerformed(evt);
            }
        });

        buttonsupprimer1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonsupprimer1.setForeground(new java.awt.Color(204, 0, 0));
        buttonsupprimer1.setText("SUPPRIMER");
        buttonsupprimer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsupprimer1ActionPerformed(evt);
            }
        });

        buttonajouter1.setBackground(new java.awt.Color(255, 255, 255));
        buttonajouter1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonajouter1.setForeground(new java.awt.Color(102, 255, 102));
        buttonajouter1.setText("AJOUTER");
        buttonajouter1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                buttonajouter1ComponentShown(evt);
            }
        });
        buttonajouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonajouter1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtidart))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtnomart))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtreference))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(buttonajouter1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonmodifier1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonsupprimer1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtquantite))))
                .addGap(5, 5, 5))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtidart, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(txtnomart, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtreference, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtquantite, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonsupprimer1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonmodifier1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonajouter1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Stock", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtetatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtetatActionPerformed
        
    }//GEN-LAST:event_txtetatActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void txtmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmailActionPerformed

    private void txtprenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomActionPerformed

    private void buttonajouterComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_buttonajouterComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonajouterComponentShown

    private void buttonajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonajouterActionPerformed
        try{
            Connect();//Connexion a la base de données
            pst = (PreparedStatement) con.prepareStatement("insert utilisateur(id_user,Nom,Prenom,Mail,Etat)values(?,?,?,?,?)");//Requete preparé
            pst.setString(1,txtid.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la base de données
            pst.setString(2,txtnom.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la base de données
            pst.setString(3,txtprenom.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la base de données
            pst.setString(4,txtmail.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la base de données
            pst.setString(5,txtetat.getSelectedItem().toString());//Methode qui permet d'assigner la valeur selectionné dans le chant SelectItem a la valeur de la bas de données
            pst.executeUpdate();//Methode qui permet d'afficher en temps réel l'ajout
            con.close();//Fermeture de la connexion a la base de données
            JOptionPane.showMessageDialog(null,"Client Ajouté");//Permet d'afficher une boite de dialogue qui affiche un message
            Table();//Affichage de la table 1 et sont contenue
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur le client n'a pas était ajouté");//Permet d'afficher une boite de dialogue qui affiche un message
        }           
    }//GEN-LAST:event_buttonajouterActionPerformed

    public void Table(){
        String [] utilisateur = {"ID","NOM","PRENOM","MAIL","ETAT"};//Permet de donner les noms de chaque colone dans la table 1
        String [] afficher = new String [5];//Fonction qui determine le nombre de colone de façon manuelle
        DefaultTableModel model = new DefaultTableModel(null,utilisateur);//Defini le model par defaut
        try {
            Connect();//Connexion a la base de données
            Statement st = (Statement) con.createStatement();//Permet d'implanter des instructions sql simple
            rs = st.executeQuery("select * from utilisateur");//Requete sql
            while(rs.next()){
                afficher[0]=rs.getString("id_user");//Afficher le resultat de la requete dans l'emplacement de la table
                afficher[1]=rs.getString("Nom");//Afficher le resultat de la requete dans l'emplacement de la table
                afficher[2]=rs.getString("Prenom");//Afficher le resultat de la requete dans l'emplacement de la table
                afficher[3]=rs.getString("Mail");//Afficher le resultat de la requete dans l'emplacement de la table
                afficher[4]=rs.getString("Etat");//Afficher le resultat de la requete dans l'emplacement de la table
                model.addRow(afficher);//Permet d'ajouter puis d'afficher toute les informations dans une ligne
            }
            jTable1.setModel(model);
            con.close();//Fermeture de la connexion
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void Table2(){
        String [] articles = {"ID","NOM","REFERENCE","QUANTITE"};//Permet de donner les noms de chaque colone dans la table 2
        String [] afficher = new String [4];//Fonction qui determine le nombre de colone de façon manuelle
        DefaultTableModel model = new DefaultTableModel(null,articles);//Defini le model par defaut
        try {
            Connect();//Connexion a la base de données
            Statement st = (Statement) con.createStatement();//Permet d'implanter des instructions sql simple
            rs = st.executeQuery("select * from article");//Requete sql
            while(rs.next()){
                afficher[0]=rs.getString("id_article");//Afficher le resultat de la requete dans l'emplacement de la table
                afficher[1]=rs.getString("Nom_art");//Afficher le resultat de la requete dans l'emplacement de la table
                afficher[2]=rs.getString("reference");//Afficher le resultat de la requete dans l'emplacement de la table
                afficher[3]=rs.getString("quantite");//Afficher le resultat de la requete dans l'emplacement de la table
                model.addRow(afficher);//Permet d'ajouter puis d'afficher toute les informations dans une ligne
            }
            jTable2.setModel(model);
            con.close();//Fermeture de la connexion
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void buttonmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmodifierActionPerformed
        try{
            Connect();//Connexion a la base de données
            pst = (PreparedStatement) con.prepareStatement("update utilisateur set Nom=?,Prenom=?,Mail=?,Etat=? where id_user=?");//Requete preparé
            pst.setString(5,txtid.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la base de données
            pst.setString(1,txtnom.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la base de données
            pst.setString(2,txtprenom.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la base de données
            pst.setString(3,txtmail.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la base de données
            pst.setString(4,txtetat.getSelectedItem().toString());//Methode qui permet d'assigner la valeur selectionné dans le chant SelectItem a la valeur de la base de données
            pst.executeUpdate();//Methode qui permet d'afficher en temps réel l'ajout
            con.close();//Fermeture de la connexion a la base de données
            JOptionPane.showMessageDialog(null,"Client Modifié");//Permet d'afficher une boite de dialogue qui affiche un message
            Table();//Affichage de la table 1 et sont contenue
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur le client n'a pas était modifié");//Permet d'afficher une boite de dialogue qui affiche un message
        }
    }//GEN-LAST:event_buttonmodifierActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        txtid.setText(model.getValueAt(i,0).toString());
        txtnom.setText(model.getValueAt(i,1).toString());
        txtprenom.setText(model.getValueAt(i,2).toString());
        txtmail.setText(model.getValueAt(i,3).toString());
        txtetat.setSelectedItem(model.getValueAt(i,4).toString());    
    }//GEN-LAST:event_jTable1MouseClicked

    private void buttonsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsupprimerActionPerformed
        try{
            Connect();//Connexion a la base de données
            pst = (PreparedStatement) con.prepareStatement("delete from utilisateur where id_user=?");//Requete preparé
            pst.setString(1,txtid.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la base de données
            pst.executeUpdate();//Methode qui permet d'afficher en temps réel la suppression
            con.close();//Fermeture de la connexion 
            JOptionPane.showMessageDialog(null,"Client Supprimé");//Permet d'afficher une boite de dialogue qui affiche un message
            Table();//Permet d'afficher la table 1 et son contenue
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur le client n'a pas était Supprimé");//Permet d'afficher une boite de dialogue qui affiche un message
        }    
    }//GEN-LAST:event_buttonsupprimerActionPerformed

    private void txtidartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidartActionPerformed

    private void txtnomartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomartActionPerformed

    private void txtquantiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantiteActionPerformed

    private void txtreferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreferenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreferenceActionPerformed

    private void buttonmodifier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmodifier1ActionPerformed
        try{
            Connect();//Connexion a la base de données
            pst = (PreparedStatement) con.prepareStatement("update article set Nom_art=?,reference=?,quantite=? where id_article=?");//Requete preparé
            pst.setString(4,txtidart.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la base de données
            pst.setString(1,txtnomart.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la base de données
            pst.setString(2,txtreference.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la base de données
            pst.setString(3,txtquantite.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la base de données
            pst.executeUpdate();//Methode qui permet d'afficher en temps réel la modification
            con.close();//Fermeture de la connexion a la base de données
            JOptionPane.showMessageDialog(null,"Article Modifié");//Permet d'afficher une boite de dialogue qui affiche un message
            Table2();//Permet d'afficher la table 2 et son contenue
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur l'article n'a pas était modifié");//Permet d'afficher une boite de dialogue qui affiche un message
        }
    }//GEN-LAST:event_buttonmodifier1ActionPerformed

    private void buttonsupprimer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsupprimer1ActionPerformed
        try{
            Connect();//Connexion a la base de données
            pst = (PreparedStatement) con.prepareStatement("delete from article where id_article=?");//Requete preparé
            pst.setString(1,txtidart.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la bas de données
            pst.executeUpdate();//Methode qui permet d'afficher en temps réel la suppression
            con.close();//Fermeture de la connexion a la base de données
            JOptionPane.showMessageDialog(null,"Article Supprimé");//Permet d'afficher une boite de dialogue qui affiche un message
            Table2();//Permet d'afficher la table 2 et son contenue
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur l'article n'a pas était Supprimé");//Permet d'afficher une boite de dialogue qui affiche un message
        } 
    }//GEN-LAST:event_buttonsupprimer1ActionPerformed

    private void buttonajouter1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_buttonajouter1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonajouter1ComponentShown

    private void buttonajouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonajouter1ActionPerformed
        try{
            Connect();//Connexion a la base de données
            pst = (PreparedStatement) con.prepareStatement("insert article(id_article,Nom_art,reference,quantite)values(?,?,?,?)");//Requete preparé
            pst.setString(1,txtidart.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la base de données
            pst.setString(2,txtnomart.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la base de données
            pst.setString(3,txtreference.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la base de données
            pst.setString(4,txtquantite.getText());//Methode qui permet d'assigner la valeur ecrite dans le chant txt a la valeur de la base de données
            pst.executeUpdate();//Methode qui permet d'afficher en temps réel l'ajout
            con.close();//Fermeture de la connexion a la base de données
            JOptionPane.showMessageDialog(null,"Article Ajouté");//Permet d'afficher une boite de dialogue qui affiche un message
            Table2();//Permet d'afficher la table 2 et son contenue
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur l'article n'a pas était ajouté");//Permet d'afficher une boite de dialogue qui affiche un message
        }
    }//GEN-LAST:event_buttonajouter1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int i = jTable2.getSelectedRow();//Methode qui permet de selectionner la ligne aprés l'action click
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();//Methode qui affiche le model sur le JTable par defaut 
        txtidart.setText(model.getValueAt(i,0).toString());//Methode qui permet d'afficher le texte selectionner dans la partie choisis 
        txtnomart.setText(model.getValueAt(i,1).toString());//Methode qui permet d'afficher le texte selectionner dans la partie choisis
        txtreference.setText(model.getValueAt(i,2).toString());//Methode qui permet d'afficher le texte selectionner dans la partie choisis
        txtquantite.setText(model.getValueAt(i,3).toString());//Methode qui permet d'afficher le texte selectionner dans la partie choisis
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stock().setVisible(true);//Permet d'afficher la page aprés la connexion
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonajouter;
    private javax.swing.JButton buttonajouter1;
    private javax.swing.JButton buttonmodifier;
    private javax.swing.JButton buttonmodifier1;
    private javax.swing.JButton buttonsupprimer;
    private javax.swing.JButton buttonsupprimer1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> txtetat;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidart;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtnomart;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtquantite;
    private javax.swing.JTextField txtreference;
    // End of variables declaration//GEN-END:variables
}
